[project]
name = "oop-hw1"
version = "1"
description = ""
authors = [
    {name = "godmayer-jdi",email = "tig774ra@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
